### Money Gather Rates
Testing gather rates for the new random echantments of [Meating Deadlines] and [Helicopter Money]

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
import sklearn as sklearn

money_gather = pd.read_csv("money_gather_rates.csv")
money_gather.head()

,Attempt,Time (Minutes),Gold,Silver,Copper,Gold Total,Silver Total,Copper Total,Enchant,DPS,Damage Total,Damage Taken,Died,Deaths
0,1,5,0.0,0.0,0.0,15.0,30.0,50.0,Test,679.0,151172.0,8668.0,False,0.0
1,2,5,1.0,75.0,62.0,25.0,2.0,83.0,None,832.0,171122.0,10581.0,False,0.0
2,3,5,2.0,10.0,3.0,36.0,54.0,87.0,None,723.0,150278.0,8418.0,False,0.0
3,4,5,1.0,62.0,70.0,30.0,57.0,35.0,None,893.0,173341.0,11098.0,False,0.0
4,5,5,2.0,5.0,2.0,15.0,98.0,71.0,Money,791.0,166508.0,9255.0,False,0.0

In [6]:
money_gather_fix = money_gather
money_gather_fix.drop(0)
money_gather_fix.drop(9:12)

SyntaxError: invalid syntax (<ipython-input-6-aafae4cb6591>, line 3)